# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godu < Formula
  desc ""
  homepage ""
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viktomas/godu/releases/download/v1.4.0/godu_1.4.0_Darwin_x86_64.tar.gz"
      sha256 "7935c45b986c1a72212249219a3985570039b88011244df8eafbe7595dedadc7"

      def install
        bin.install "godu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viktomas/godu/releases/download/v1.4.0/godu_1.4.0_Darwin_arm64.tar.gz"
      sha256 "71dad2dd758dc51f223f0f759d799a2eab60b8a2b44be176143c1166937f8563"

      def install
        bin.install "godu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/viktomas/godu/releases/download/v1.4.0/godu_1.4.0_Linux_x86_64.tar.gz"
      sha256 "b801cc55bf805d7449c29d4dfffee9102fe7de8204c940ee304f63c93b86e447"

      def install
        bin.install "godu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viktomas/godu/releases/download/v1.4.0/godu_1.4.0_Linux_arm64.tar.gz"
      sha256 "094497600b3072db05dd84193dfc0c25f95f899e0edb097924eb384d75c57aa1"

      def install
        bin.install "godu"
      end
    end
  end
end
