# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godu < Formula
  desc ""
  homepage ""
  version "1.5.2"

  on_macos do
    on_intel do
      url "https://github.com/viktomas/godu/releases/download/v1.5.2/godu_1.5.2_darwin_amd64.tar.gz"
      sha256 "ea3979ead720076945a4b3703cf07f31464744b3b69da60e5fffb8ff014b5502"

      def install
        bin.install "godu"
      end
    end
    on_arm do
      url "https://github.com/viktomas/godu/releases/download/v1.5.2/godu_1.5.2_darwin_arm64.tar.gz"
      sha256 "0a80226e7ba043c1c58953899ca509f0bea2aa3c79c877ab630f1c4f387d6983"

      def install
        bin.install "godu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/viktomas/godu/releases/download/v1.5.2/godu_1.5.2_linux_amd64.tar.gz"
        sha256 "17017e52f2b36aa41697ecf556c4f41a53e8fa34da49494aa2129d7384e8fec4"

        def install
          bin.install "godu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/viktomas/godu/releases/download/v1.5.2/godu_1.5.2_linux_arm64.tar.gz"
        sha256 "2a16dbea0e5ec66bfc5bbed55679ede5ce2b4c33ef782827f7d27b1d597f0e38"

        def install
          bin.install "godu"
        end
      end
    end
  end
end
