# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godu < Formula
  desc ""
  homepage ""
  version "1.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/viktomas/godu/releases/download/v1.4.1/godu_1.4.1_Darwin_arm64.tar.gz"
      sha256 "dce7969b56537c2abf475ee394e76af6d1a1b0f412e62be2352906299e8f3d8e"

      def install
        bin.install "godu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/viktomas/godu/releases/download/v1.4.1/godu_1.4.1_Darwin_x86_64.tar.gz"
      sha256 "0bbaa0dd17a751c8aab27ba1f6a30a89398f616f06c0b4d791be8f5bc02591fb"

      def install
        bin.install "godu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/viktomas/godu/releases/download/v1.4.1/godu_1.4.1_Linux_x86_64.tar.gz"
      sha256 "26001c9e86044948eba7ddf7c2d7dab38015a7540400df21d76d01bfb8bdf059"

      def install
        bin.install "godu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viktomas/godu/releases/download/v1.4.1/godu_1.4.1_Linux_arm64.tar.gz"
      sha256 "eb3214ba5b31e778ad3501116730181e49d7809669195beff8a1c1267214589b"

      def install
        bin.install "godu"
      end
    end
  end
end
